name: Test
on: pull_request
jobs:
  composer:
    name: Composer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          php-version: '8.3'
      - name: Validate composer.json and composer.lock
        run: composer validate
      - name: Install dependencies
        run: composer install --prefer-dist --no-scripts -a -n --ignore-platform-reqs --no-progress
